In [1]:
def unit_conversion():
    """
    Performs unit conversions for length, weight, and volume.

    The function prompts the user to:
    1. Select the type of conversion (length, weight, volume).
    2. Enter the value to convert.
    3. Choose the specific conversion direction.

    Parameters:
    None

    Returns:
    None
    Displays the converted result or error messages directly.
    """
    try:
        print("Select Conversion Type:")
        print("1. Length")
        print("2. Weight")
        print("3. Volume")

        choice = input("Enter your choice (1/2/3): ")
        value = float(input("Enter the value to convert: "))

        if choice == "1":
            print("\nLength Conversion")
            print("1. Meters (m) → Feet (ft)")
            print("2. Feet (ft) → Meters (m)")

            option = input("Select option (1/2): ")

            if option == "1":
                result = value * 3.28084
                print("Converted value:", result, "ft")

            elif option == "2":
                result = value / 3.28084
                print("Converted value:", result, "m")

            else:
                print("Error: Invalid length conversion option.")

        elif choice == "2":
            print("\nWeight Conversion")
            print("1. Kilograms (kg) → Pounds (lbs)")
            print("2. Pounds (lbs) → Kilograms (kg)")

            option = input("Select option (1/2): ")

            if option == "1":
                result = value * 2.20462
                print("Converted value:", result, "lbs")

            elif option == "2":
                result = value / 2.20462
                print("Converted value:", result, "kg")

            else:
                print("Error: Invalid weight conversion option.")

        elif choice == "3":
            print("\nVolume Conversion")
            print("1. Liters (L) → Gallons (gal)")
            print("2. Gallons (gal) → Liters (L)")

            option = input("Select option (1/2): ")

            if option == "1":
                result = value * 0.264172
                print("Converted value:", result, "gal")

            elif option == "2":
                result = value / 0.264172
                print("Converted value:", result, "L")

            else:
                print("Error: Invalid volume conversion option.")

        else:
            print("Error: Unsupported conversion type.")

    except ValueError:
        print("Error: Please enter a valid numeric value.")

In [4]:
unit_conversion()

Select Conversion Type:
1. Length
2. Weight
3. Volume
Enter your choice (1/2/3): 1
Enter the value to convert: 20

Length Conversion
1. Meters (m) → Feet (ft)
2. Feet (ft) → Meters (m)
Select option (1/2): 1
Converted value: 65.6168 ft


In [5]:
def find_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Sum of the numbers.
    """
    return sum(numbers)


def find_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Average of the numbers.
    """
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Finds the maximum number in a list.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Largest number in the list.
    """
    return max(numbers)


def find_minimum(numbers):
    """
    Finds the minimum number in a list.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Smallest number in the list.
    """
    return min(numbers)


def calculation():
    """
    Prompts the user to select a mathematical operation and input a list of numbers.
    Performs the selected operation and prints the result.
    Handles invalid input such as non-numeric values or empty lists.
    """

    try:
        print("Select Operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")

        choice = input("Enter your choice (1/2/3/4): ")

        user_input = input("Enter numbers separated by spaces: ")

        numbers = [float(num) for num in user_input.split()]

        if len(numbers) == 0:
            raise ValueError("Empty list")

        if choice == "1":
            print("Sum:", find_sum(numbers))

        elif choice == "2":
            print("Average:", find_average(numbers))

        elif choice == "3":
            print("Maximum:", find_maximum(numbers))

        elif choice == "4":
            print("Minimum:", find_minimum(numbers))

        else:
            print("Invalid operation selected.")

    except ValueError:
        print("Error: Please enter valid numeric values.")

In [6]:
calculation()

Select Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1/2/3/4): 4
Enter numbers separated by spaces: 50 70
Minimum: 50.0


In [7]:
def extract_every_other(lst):
    """
    Extracts every other element from a list starting from the first element.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every other element from the original list.
    """
    return lst[::2]



In [8]:
extract_every_other([1,2,3,4,5,6])

[1, 3, 5]

In [9]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list starting from index 'start'
    and ending at index 'end' (inclusive).

    Parameters:
    lst (list): The original list.
    start (int): Starting index.
    end (int): Ending index.

    Returns:
    list: A sublist from start to end (inclusive).
    """
    return lst[start:end+1]

In [10]:
numbers = [1, 2, 3, 4, 5, 6]
result = get_sublist(numbers, 2, 4)
print(result)

[3, 4, 5]


In [11]:
def reverse_list(lst):
    """
    Reverses a list using slicing.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing the elements of the original list in reverse order.
    """
    return lst[::-1]

In [12]:
reverse_list([1,2,3,4,5])

[5, 4, 3, 2, 1]

In [25]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list using slicing.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list without the first and last elements.
    """
    return lst[1:-1]

In [26]:
remove_first_last([1,2,3,4,5])


[2, 3, 4]

In [27]:
def get_first_n(lst, n):
    """
    Returns the first n elements from a list using slicing.

    Parameters:
    lst (list): The input list.
    n (int): The number of elements to extract from the beginning.

    Returns:
    list: A new list containing the first n elements of the input list.
    """
    return lst[:n]

In [29]:
get_first_n([0,7,8,10,22], 2)

[0, 7]

In [35]:
def get_last_n(lst, n):
  return lst[-n:]

In [36]:
get_last_n([0,7,8,10,22], 3)

[8, 10, 22]

In [37]:
def reverse_skip(lst):
    """
    Extracts every second element from the list in reverse order,
    starting from the second-to-last element.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every second element from the second-to-last element moving backward.
    """
    return lst[-2::-2]

In [38]:
reverse_skip([1,2,3,4,5,6])


[5, 3, 1]

**Numpy Exercise**

In [39]:
import numpy as np

**Basic Vector and Matrix Operation with Numpy.**

In [40]:
empty_array = np.empty((2, 2))
print(empty_array)

[[2.30796115e-315 0.00000000e+000]
 [1.03455747e-259 0.00000000e+000]]


In [41]:
ones_array = np.ones((4, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [42]:
shape = (3, 3)
fill_value = 7
filled_array = np.full(shape, fill_value, dtype=int)
print(filled_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [43]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(original_array)
print(zeros_like_array)

[[0 0 0]
 [0 0 0]]


In [44]:
ones_like_array = np.ones_like(original_array)
print(ones_like_array)

[[1 1 1]
 [1 1 1]]


In [45]:
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print(array_from_list)

[1 2 3 4]


**Array Manipulation: Numerical Ranges and Array indexing:**

In [46]:
arr1 = np.arange(10, 50)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [47]:
arr2 = np.arange(9).reshape(3, 3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [48]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
random_array = np.random.random(30)  # random values between 0 and 1
mean_value = random_array.mean()
print("Array:", random_array)
print("Mean:", mean_value)

Array: [0.62060267 0.85423035 0.36985076 0.39220421 0.80699276 0.6754346
 0.88320904 0.55955321 0.22651963 0.24017331 0.0280206  0.35242476
 0.81590855 0.45040064 0.79962636 0.10387735 0.63740369 0.51687451
 0.16637614 0.73821452 0.77008685 0.89544974 0.11731265 0.44337812
 0.19122819 0.15891042 0.45051688 0.58678507 0.09535148 0.2952035 ]
Mean: 0.47473735277507695


In [50]:
random_10x10 = np.random.random((10, 10))
min_val = random_10x10.min()
max_val = random_10x10.max()
print("Min:", min_val)
print("Max:", max_val)

Min: 0.008101702843509861
Max: 0.993958452434497


In [51]:
zero_array = np.zeros(10)
zero_array[4] = 1  # index 4 is the 5th element
print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [53]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [54]:
n = 5  # example size
border_array = np.ones((n, n))
border_array[1:-1, 1:-1] = 0
print(border_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [55]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Array Operations:**

In [56]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [57]:
add_xy = x + y
print("x + y =\n", add_xy)

x + y =
 [[ 6  8]
 [10 13]]


In [58]:
sub_xy = x - y
print("x - y =\n", sub_xy)

x - y =
 [[-4 -4]
 [-4 -3]]


In [59]:
mul_x = x * 3  # multiply x by 3
print("x * 3 =\n", mul_x)

x * 3 =
 [[ 3  6]
 [ 9 15]]


In [60]:
square_x = x ** 2
print("x squared =\n", square_x)

x squared =
 [[ 1  4]
 [ 9 25]]


In [61]:
dot_vw = np.dot(v, w)
print("v · w =", dot_vw)

v · w = 219


In [62]:
dot_xv = np.dot(x, v)
print("x · v =", dot_xv)

x · v = [29 77]


In [63]:
dot_xy = np.dot(x, y)
print("x · y =\n", dot_xy)


x · y =
 [[19 22]
 [50 58]]


In [64]:
concat_xy_rows = np.concatenate((x, y), axis=0)
print("Concatenate x and y along rows:\n", concat_xy_rows)

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [65]:
v_reshaped = v.reshape(2, 1)
w_reshaped = w.reshape(2, 1)
concat_vw_cols = np.concatenate((v_reshaped, w_reshaped), axis=1)
print("Concatenate v and w along columns:\n", concat_vw_cols)

Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]


In [66]:
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenate x and v:\n", concat_xv)
except ValueError as e:
    print("Error:", e)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [67]:
v_reshaped = v.reshape(1, 2)
concat_xv_fixed = np.concatenate((x, v_reshaped), axis=0)
print("Concatenate x and v (reshaped) along rows:\n", concat_xv_fixed)

Concatenate x and v (reshaped) along rows:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


**Matrix Operations:**

In [68]:
A = np.array([[3, 4],
              [7, 8]])
B = np.array([[5, 3],
              [2, 1]])

In [69]:
A_inv = np.linalg.inv(A)
I_check = np.dot(A, A_inv)
print("A · A⁻¹ =\n", I_check)

A · A⁻¹ =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [70]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("A · B =\n", AB)
print("B · A =\n", BA)
print("Are they equal?", np.array_equal(AB, BA))

A · B =
 [[23 13]
 [51 29]]
B · A =
 [[36 44]
 [13 16]]
Are they equal? False


In [71]:
AB_T = np.dot(A, B).T
B_TA_T = np.dot(B.T, A.T)
print("(AB)ᵀ =\n", AB_T)
print("Bᵀ · Aᵀ =\n", B_TA_T)
print("Are they equal?", np.array_equal(AB_T, B_TA_T))

(AB)ᵀ =
 [[23 51]
 [13 29]]
Bᵀ · Aᵀ =
 [[23 51]
 [13 29]]
Are they equal? True


In [72]:
A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3, 1, -1]])

B_sys = np.array([-1, -3, 9])

In [73]:
A_inv_sys = np.linalg.inv(A_sys)
X = np.dot(A_inv_sys, B_sys)
print("Solution [x, y, z] =", X)

Solution [x, y, z] = [ 2.  1. -2.]


In [74]:
X_solve = np.linalg.solve(A_sys, B_sys)
print("Solution using linalg.solve:", X_solve)

Solution using linalg.solve: [ 2.  1. -2.]


**Experiment: How Fast is Numpy?**

In [75]:
import time
import numpy as np

# 1. Element-wise Addition

size = 1_000_000

# Python lists
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
list_add = [a + b for a, b in zip(list1, list2)]
end = time.time()
print("Python List Addition Time:", end - start, "seconds")

# NumPy arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
arr_add = arr1 + arr2
end = time.time()
print("NumPy Array Addition Time:", end - start, "seconds")

# 2. Element-wise Multiplication

# Python lists
start = time.time()
list_mul = [a * b for a, b in zip(list1, list2)]
end = time.time()
print("Python List Multiplication Time:", end - start, "seconds")

# NumPy arrays
start = time.time()
arr_mul = arr1 * arr2
end = time.time()
print("NumPy Array Multiplication Time:", end - start, "seconds")

# 3. Dot Product

# Python lists
start = time.time()
dot_list = sum(a * b for a, b in zip(list1, list2))
end = time.time()
print("Python List Dot Product Time:", end - start, "seconds")

# NumPy arrays
start = time.time()
dot_array = np.dot(arr1, arr2)
end = time.time()
print("NumPy Array Dot Product Time:", end - start, "seconds")

# 4. Matrix Multiplication

matrix_size = 1000

# Python lists
mat1 = [[j for j in range(matrix_size)] for i in range(matrix_size)]
mat2 = [[j for j in range(matrix_size)] for i in range(matrix_size)]

start = time.time()
# Manual matrix multiplication using lists
result = [[sum(mat1[i][k] * mat2[k][j] for k in range(matrix_size))
           for j in range(matrix_size)]
          for i in range(matrix_size)]
end = time.time()
print("Python List Matrix Multiplication Time:", end - start, "seconds")

# NumPy arrays
np_mat1 = np.arange(matrix_size*matrix_size).reshape(matrix_size, matrix_size)
np_mat2 = np.arange(matrix_size*matrix_size).reshape(matrix_size, matrix_size)

start = time.time()
np_result = np.dot(np_mat1, np_mat2)
end = time.time()
print("NumPy Array Matrix Multiplication Time:", end - start, "seconds")

Python List Addition Time: 0.08418583869934082 seconds
NumPy Array Addition Time: 0.004825115203857422 seconds
Python List Multiplication Time: 0.23425626754760742 seconds
NumPy Array Multiplication Time: 0.006166696548461914 seconds
Python List Dot Product Time: 0.08472847938537598 seconds
NumPy Array Dot Product Time: 0.0019259452819824219 seconds
Python List Matrix Multiplication Time: 192.11898183822632 seconds
NumPy Array Matrix Multiplication Time: 2.4401137828826904 seconds


**Observations**

NumPy is significantly faster than Python lists for all element-wise operations and dot products because:

NumPy uses vectorized operations in C.

Python lists use pure Python loops, which are slow.

Dot product is particularly slow for Python lists because it performs 1,000,000 multiplications and additions in Python, whereas NumPy does it in compiled code.

Matrix multiplication with Python lists of size 1000×1000 is impractical, it will take tens of minutes, while NumPy completes it in less than a second.

Speedup increases with array size — larger arrays make NumPy’s advantage even more visible.

**Conclusion**

For large numerical computations, always use NumPy arrays instead of Python lists.

Python lists are okay for small-scale calculations, but for millions of elements or matrix operations, NumPy is orders of magnitude faster.